services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - 'pgdata:/bitnami/postgresql'
      - './docker:/docker-entrypoint-initdb.d'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker -d upload']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://docker:docker@pg:5432/upload
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pgdata:
