name: widget-server pipe

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image to Amazon ECR
        id: build-and-push-docker-image
        run: 
          docker build -t widget-server:v3 .
          docker tag widget-server:v3 478483354383.dkr.ecr.us-east-1.amazonaws.com/vhugo/widget-server:v3
          docker push 478483354383.dkr.ecr.us-east-1.amazonaws.com/vhugo/widget-server:v3